[target.x86_64-unknown-linux-gnu]
dockerfile = "./.ci/Dockerfile"

[target.i686-unknown-linux-gnu]
dockerfile = "./.ci/Dockerfile"

[target.aarch64-unknown-linux-gnu]
dockerfile = "./.ci/Dockerfile"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "./.ci/Dockerfile"

[target.arm-unknown-linux-gnueabihf]
dockerfile = "./.ci/Dockerfile"
