name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build_and_release:
    name: "Build & Release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            file-tag: "x86_64"
            strip: "x86_64-linux-gnu-strip"
          - target: i686-unknown-linux-gnu
            file-tag: "i686"
            strip: "i686-linux-gnu-strip"
          - target: aarch64-unknown-linux-gnu
            file-tag: "aarch64"
            strip: "aarch64-linux-gnu-strip"
          - target: armv7-unknown-linux-gnueabihf
            file-tag: "armv7l"
            strip: "arm-linux-gnueabihf-strip"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package tarball
        run: >-
          tar --lzip -cf 'rvlink-bridge.${{ matrix.file-tag }}.tar.lz' -C target/${{ matrix.target }}/release rvlink-bridge

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ""
          draft: false
          prerelease: false

      - name: Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./rvlink-bridge.${{ matrix.file-tag }}.tar.lz
          asset_name: rvlink-bridge.${{ matrix.file-tag }}.tar.lz
          asset_content_type: application/x-gtar
