name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build_and_release:
    name: "Build & Release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            file-tag: "x86_64"
            strip: "x86_64-linux-gnu-strip"
          - target: i686-unknown-linux-gnu
            file-tag: "i686"
            strip: "i686-linux-gnu-strip"
          - target: aarch64-unknown-linux-gnu
            file-tag: "aarch64"
            strip: "aarch64-linux-gnu-strip"
          - target: armv7-unknown-linux-gnueabihf
            file-tag: "armv7l"
            strip: "arm-linux-gnueabihf-strip"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package tarball
        run: >-
          tar -cJf 'rvlink-bridge.${{ matrix.file-tag }}.tar.xz' -C target/${{ matrix.target }}/release rvlink-bridge

      - name: Create release with assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./rvlink-bridge.*.tar.xz
